# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bf2620cd3318239956bf1d5a1bb588d476dd11591f2e332b6c688df1ceb096eb40cc0019efa451eaef6a5f204c63f33ab358af69f0fbf2c6c4dd2bd49d34caf

test:
  secret_key_base: 48b74ef23d0e3022746eb19ee1888e79ecc964fb2cb80252a918c0a516f07bfef869ff16e1bf27faefd0fc209e0f092264624a075759d3f8cece2cbd98b5329e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
